Repository znuny/Znuny, pull requests merged in 2021-11, with the labels that each got.

#133 Prevents error message "no TicketID" on sending an answer if no TicketID exists.
  var/httpd/htdocs/js/Core.Agent.TicketCompose.js
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - verified, 3 - wait for merge, 2 - Frontend, Znuny Feature

#136 Add option ''--no-tablespaces' to scripts/backup.pl.
  scripts/backup.pl
Labels: 1 - 🚀 feature, Znuny LTS, 3 - verified, 3 - wait for merge, 2 - Backend, Znuny Feature, Znuny Latest

#171 Sector Nord AG: Replaced hardcoded attributes with a dynamic Sysconfig in Kernel/System/Ticket/Event/NotificationEvent.pm
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/System/Ticket/Event/NotificationEvent.pm
Labels: 3 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - Backend, Znuny Feature, Znuny Latest

#174 Added DefaultValue to dynamic fields in Application_for_leave_pre process to prevent possible error messages via _SanitizeConfig.
  var/processes/examples/Application_for_leave_pre.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - verified, 2 - Backend, Znuny Feature, Znuny Latest
