Repository znuny/Znuny, pull requests merged in 2021-04, with the labels that each got.

#52 Fix visual minor - missing spacing when adding new values.
  Kernel/Output/HTML/Templates/Standard/AdminDynamicFieldDropdown.tt
  Kernel/Output/HTML/Templates/Standard/AdminGenericInterfaceMappingXSLT.tt
Labels: 1 - 🐞 bug 🐞, 2 - Frontend, 3 - wait for merge

#39 Update cpan-lib LWP::Protocol::https
  Kernel/cpan-lib/LWP/Protocol/https.pm
Labels: 1 - 🆙 dependency upgrade, 2 - cpan-lib, 3 - wait for merge

#40 Update libwww-perl (LWP::UserAgent et al)
  Kernel/cpan-lib/LWP.pm
  Kernel/cpan-lib/LWP/Authen/Basic.pm
  Kernel/cpan-lib/LWP/Authen/Digest.pm
  Kernel/cpan-lib/LWP/Authen/Ntlm.pm
  Kernel/cpan-lib/LWP/ConnCache.pm
  Kernel/cpan-lib/LWP/Debug.pm
  Kernel/cpan-lib/LWP/Debug/TraceHTTP.pm
  Kernel/cpan-lib/LWP/DebugFile.pm
  Kernel/cpan-lib/LWP/MemberMixin.pm
  Kernel/cpan-lib/LWP/Protocol.pm
  Kernel/cpan-lib/LWP/Protocol/cpan.pm
  Kernel/cpan-lib/LWP/Protocol/data.pm
  Kernel/cpan-lib/LWP/Protocol/file.pm
  Kernel/cpan-lib/LWP/Protocol/ftp.pm
  Kernel/cpan-lib/LWP/Protocol/gopher.pm
  Kernel/cpan-lib/LWP/Protocol/http.pm
  Kernel/cpan-lib/LWP/Protocol/loopback.pm
  Kernel/cpan-lib/LWP/Protocol/mailto.pm
  Kernel/cpan-lib/LWP/Protocol/nntp.pm
  Kernel/cpan-lib/LWP/Protocol/nogo.pm
  Kernel/cpan-lib/LWP/RobotUA.pm
  Kernel/cpan-lib/LWP/Simple.pm
  Kernel/cpan-lib/LWP/UserAgent.pm
Labels: 1 - 🆙 dependency upgrade, 2 - cpan-lib, 3 - verified

#42 Fix URL to product in HTTP Headers
  Kernel/Output/HTML/Templates/Standard/HTTPHeaders.tt
Labels: 1 - 🐞 bug 🐞, 2 - Znuny, 3 - verified

#55 Fixed uninitialized value in pattern match warning for the TicketCreate operation (#55).
  Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm
Labels: 1 - 💎 code quality, 2 - CodeStyle, 3 - wait for merge

#53 Fixed webservice creation only uses valid webservices to check if the name is already used (#53).
  Kernel/Modules/AdminGenericInterfaceWebservice.pm
Labels: 1 - 🐞 bug 🐞, 2 - Backend, 3 - wait for merge

#56 Fixed webservice console commands only use valid webservices to check if the name is already used (#56).
  Kernel/System/Console/Command/Admin/WebService/Add.pm
  Kernel/System/Console/Command/Admin/WebService/Delete.pm
  Kernel/System/Console/Command/Admin/WebService/Dump.pm
  Kernel/System/Console/Command/Admin/WebService/List.pm
  Kernel/System/Console/Command/Admin/WebService/Update.pm
Labels: 1 - 🐞 bug 🐞, 2 - System/Console, 3 - wait for merge

#57 Fixed uninitialized value in pattern match warning for the TicketUpdate operation (#57).
  Kernel/GenericInterface/Operation/Ticket/TicketUpdate.pm
Labels: 1 - 💎 code quality, 2 - CodeStyle, 3 - wait for merge

#54 Changed CommunicationChannel to optional.
  Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm
  Kernel/GenericInterface/Operation/Ticket/TicketUpdate.pm
Labels: 1 - 🚀 feature, 2 - GenericInterface, 3 - wait for merge

#46 Improved POD in Priority.pm (#46).
  Kernel/System/Priority.pm
Labels: 1 - 💎 code quality, 2 - documentation, 3 - wait for merge

#20 Rewrite some weird code in UpdateSessionID()
  Kernel/System/AuthSession.pm
Labels: 1 - 💎 code quality, 2 - System/AuthSession, 3 - wait for reviewer
