Repository znuny/Znuny, pull requests merged in 2021-10, with the labels that each got.

#146 Added initial config for Frontend::Navigation###AdminCustomerUserCustomer###001-Framework
  Kernel/Config/Files/XML/Framework.xml
Labels: 1 - 🚀 feature, 3 - verified, 3 - wait for merge, 2 - Frontend, 2 - System/SysConfig, Znuny Feature

#72 Fixed error "Can't sign: unable to write 'random state'" if sending emails signed with S/MIME. – OTRS bug #14522
  Kernel/System/Crypt/SMIME.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - verified, 3 - wait for merge, 2 - Backend, Znuny Feature, Znuny Latest

#143 Sector Nord AG: Added ticket event and event module 'TicketAllChildrenClosed'
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/System/Ticket/Event/TicketAllChildrenClosed.pm
  scripts/test/Ticket/Event/TicketAllChildrenClosed.t
Labels: 1 - 🚀 feature, 3 - wait for reviewer, Znuny Feature

#45 Disable connecting external RSS during unit testing
  scripts/test/Frontend/Basic.t
  scripts/test/Frontend/PictureUpload.t
Labels: Znuny LTS, 3 - verified, 3 - clarification, 1 - 💎 code quality, 3 - wait for merge, 2 - UnitTest, Znuny Feature
