Repository znuny/Znuny, pull requests merged in 2021-08, with the labels that each got.

#89 Added SysConfig option to enable week numbers in the datepicker widget.
  Kernel/Config/Files/XML/Framework.xml
  Kernel/Output/HTML/Layout.pm
  var/httpd/htdocs/js/Core.UI.Datepicker.js
Labels: 1 - 🚀 feature, 3 - verified, 3 - wait for merge, 2 - Frontend, Znuny Feature

#67 Adding new autocomplete values to input fields
  Kernel/Output/HTML/Preferences/Password.pm
  Kernel/Output/HTML/Templates/Standard/AdminMailAccount.tt
  Kernel/Output/HTML/Templates/Standard/AdminSMIME.tt
  Kernel/Output/HTML/Templates/Standard/AgentPreferences.tt
  Kernel/Output/HTML/Templates/Standard/CustomerLogin.tt
  Kernel/Output/HTML/Templates/Standard/CustomerPreferences.tt
  Kernel/Output/HTML/Templates/Standard/Login.tt
Labels: 3 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - Frontend, Znuny Feature

#111 Fixed #107 - AgentTicketEmailOutbound "Empty subject" notification is not translated.
  Kernel/Modules/AgentTicketEmailOutbound.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - verified, 3 - wait for merge, 2 - Frontend, Znuny Feature, Znuny Last

#51 Fix double encoding for dynamic field filters in ticket overviews
  Kernel/Output/HTML/Dashboard/TicketGeneric.pm
  Kernel/Output/HTML/TicketOverview/Small.pm
  scripts/test/Selenium/Output/Dashboard/TicketGenericFilter.t
  scripts/test/Selenium/Output/Ticket/OverviewSmall.t
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - verified, 3 - wait for merge, 2 - Frontend, Znuny Feature, Znuny Last

#120 Added SessionRemove to GenericInterface.
  Kernel/Config/Files/XML/GenericInterface.xml
  Kernel/GenericInterface/Operation/Session/SessionRemove.pm
  scripts/test/GenericInterface/Operation/Session/SessionRemove.t
Labels: 1 - 🚀 feature, 3 - verified, 3 - wait for merge, 2 - System/GenericInterface, Znuny Feature

#116 Fixed storage switch only executable from main directory.
  Kernel/System/Console/Command/Admin/Article/StorageSwitch.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - verified, 2 - System/Console, 3 - wait for merge, Znuny Feature, Znuny Latest
