Repository znuny/Znuny, pull requests merged in 2022-08, with the labels that each got.

#272 Changed user-id from element-id to custom data-attribute
  Kernel/Output/HTML/Templates/Standard/AgentTicketZoom/MentionsTable.tt
  var/httpd/htdocs/js/Znuny.Agent.MentionAction.js
Labels: 4 - verified

#273 Changed agent-entry in the ticket-history for mention-notifications to responsible agent
  Kernel/System/Mention.pm
  Kernel/System/Ticket/Event/Mentions.pm
  scripts/test/Mentions/Mentions.t
  scripts/test/Mentions/MentionsPermissionCheck.t
Labels: 1 - 🐞 bug 🐞, 4 - verified

#278 Fixed evaluation of parameter TicketID in Kernel::Output::HTML::Article::Base::ArticleActions (by maxence).
  Kernel/Output/HTML/Article/Base.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified

#175 Added SysConfig setting to enable the 'exact customer ID' search field as a default field in the ticket search.
  Kernel/Config/Files/XML/Ticket.xml
Labels: 1 - 🚀 feature, 4 - clarification, 3 - wait for reviewer, 2 - System/TicketSearch, Znuny Feature

#280 Added CustomerTicketMessage to ACLKeysLevel3::Actions###100-Default
  Kernel/Config/Files/XML/Ticket.xml
Labels: 4 - verified, 1 - 💎 code quality

#271 Enabled conditional display of pending time for process tickets.
  var/httpd/htdocs/js/Core.Agent.TicketProcess.js
  var/httpd/htdocs/js/Znuny.Form.Input.js
Labels: 4 - verified

#176 Added events for article email backend transmission errors.
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/System/Ticket/Article/Backend/Email.pm
  scripts/test/Ticket/Article/Backend/TransmissionLog.t
Labels: 1 - 🐞 bug 🐞, 1 - 🚀 feature, 4 - verified, 2 - System/Email, 3 - wait for reviewer

#276 SectorNordAG: Bugfix for process and process templates
  Kernel/Modules/AgentTicketProcess.pm
  Kernel/Modules/CustomerTicketProcess.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Backend
