Repository znuny/Znuny, pull requests merged in 2022-10, with the labels that each got.

#304 Renamed changed Settings from FrontendRichText::Path to Frontend::RichText::Path.
  Kernel/Output/HTML/Templates/Standard/CustomerFooterJS.tt
  Kernel/Output/HTML/Templates/Standard/FooterJS.tt
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 2 - Backend, Znuny Feature

#177 Integrate DashboardMyLastChangedTickets.
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/Output/HTML/Dashboard/MyLastChangedTickets.pm
  Kernel/Output/HTML/Templates/Standard/AgentDashboardMyLastChangedTickets.tt
Labels: 1 - 🚀 feature, 4 - verified, 2 - Frontend, Znuny Feature

#311 Fixed "Invalid date/time string" errors in otrs.Daemon.pl.
  Kernel/System/Daemon/SchedulerDB.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 3 - wait for merge, 2 - Backend

#302 Sector Nord AG: Processmanagement AppointmentCreate - removed unnecessary filter on read permission for CalendarName.
  Kernel/System/ProcessManagement/TransitionAction/AppointmentCreate.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Backend, Znuny Feature, 2 - System
