Repository znuny/Znuny, pull requests merged in 2022-09, with the labels that each got.

#147 Bugfix and Feature for 0050-CIC-CustomerUserList
  Kernel/Output/HTML/Dashboard/CustomerUserList.pm
  Kernel/Output/HTML/Templates/Standard/AgentDashboardCustomerUserList.tt
Labels: 1 - 🐞 bug 🐞, 1 - 🚀 feature, 4 - verified, 2 - Frontend, Znuny Feature

#284 Added 'AdditionalSearchParameters' to Toolbar TicketSearchFulltext to define the standard search more precisely.
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/Output/HTML/Templates/Standard/Header.tt
Labels: 1 - 🚀 feature, 4 - verified, 4 - clarification, 2 - Backend

#283 Added Selenium tests to the GitHub workflow.
  .github/workflows/ci.yaml
  .github/workflows/ci/config-selenium.sh
  .github/workflows/ci/setup.sh
  Kernel/System/UnitTest/Selenium.pm
Labels: 4 - verified, 1 - 💎 code quality, 2 - GitHub, 2 - UnitTest

#197 Improved nonexistent and invalid service names handling in postmaster filters.
  Kernel/System/PostMaster/FollowUp.pm
  Kernel/System/PostMaster/NewTicket.pm
  Kernel/System/Service.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 1 - 💎 code quality, Znuny Feature, 2 - System

#178 Fixed log flooding via Net::LDAP. Reduction of LDAP_SIZELIMIT_EXCEEDED messages.
  Kernel/System/CustomerUser/LDAP.pm
Labels: Znuny LTS, 4 - verified, 1 - 💎 code quality, 2 - Backend, Znuny Feature, 4 - internal Issue/MR

#95 Changed previous upstream name to 'Internal' channel name.
  Kernel/Config/Files/XML/Framework.xml
Labels: 4 - verified, 4 - clarification, 1 - 💎 code quality, 2 - System

#74 Fixed LDAP user sync.
  Kernel/System/Auth/Sync/LDAP.pm
  Kernel/System/User.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Backend

#181 Added AppointmentFilter to AgentAppointmentCalendarOverview.
  Kernel/Output/HTML/Templates/Standard/AgentAppointmentCalendarOverview.tt
  var/httpd/htdocs/js/Core.Agent.AppointmentCalendar.js
Labels: 1 - 🚀 feature, 4 - verified, 2 - Frontend, Znuny Feature

#291 Fixed activity dialog error on missing templates (StandardTemplate).
  var/httpd/htdocs/js/Core.Agent.Admin.ProcessManagement.js
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Frontend

#290 Fixed time units always mandatory in AgentTicketBulk
  Kernel/Modules/AgentTicketBulk.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Modules

#288 Fixed Selenium tests.
  Kernel/Output/HTML/Templates/Standard/AgentTicketZoom/LinkTable.tt
  Kernel/Output/HTML/Templates/Standard/AgentTicketZoom/MentionsTable.tt
  scripts/test/Selenium/Agent/Admin/Admin.t
  scripts/test/Selenium/Agent/Admin/AdminCloudServices.t
  scripts/test/Selenium/Agent/Admin/AdminDynamicField.t
  scripts/test/Selenium/Agent/Admin/AdminGenericAgent.t
  scripts/test/Selenium/Agent/Admin/AdminLog.t
  scripts/test/Selenium/Agent/Admin/AdminPackageManager.t
  scripts/test/Selenium/Agent/Admin/AdminSMIME.t
  scripts/test/Selenium/Agent/Admin/AdminSort.t
  scripts/test/Selenium/Agent/Admin/AdminSupportDataCollector.t
  scripts/test/Selenium/Agent/Admin/AdminSystemConfigurationExampleArray.t
  scripts/test/Selenium/Agent/Admin/AdminSystemConfigurationExampleBasic.t
  scripts/test/Selenium/Agent/Admin/AdminSystemConfigurationExampleHash.t
  scripts/test/Selenium/Agent/Admin/DynamicField/AdminDynamicFieldScreenConfiguration.t
  scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t
  scripts/test/Selenium/Agent/AgentTicketBulk.t
  scripts/test/Selenium/Agent/AgentTicketCompose.t
  scripts/test/Selenium/Agent/AgentTicketZoom.t
  scripts/test/Selenium/Agent/Ajax/ErrorHandling.t
  scripts/test/Selenium/Output/Dashboard/News.t
  scripts/test/Selenium/Output/TicketZoom/LinkTable.t
Labels: 1 - 🐞 bug 🐞, 1 - 💎 code quality, 3 - wait for reviewer, 2 - UnitTest, Znuny Feature

#292 Fixed visible PluginContainer (AppointmentCalendar) when empty.
  var/httpd/htdocs/js/Core.Agent.AppointmentCalendar.js
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Frontend

#293 Improved SeleniumTest - ErrorHandling.t uses more stable selectors.
  scripts/test/Selenium/Agent/Ajax/ErrorHandling.t
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 2 - UnitTest

#296 Sector Nord AG: Fixed bug - hour 0 is not possible in the default settings for TimeWorkingHours.
  Kernel/System/SysConfig/ValueType/WorkingHours.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 1 - 💎 code quality, Znuny Feature
