Repository znuny/Znuny, pull requests merged in 2023-01, with the labels that each got.

#331 Sector Nord AG: Fixed popup description long were cut off in Customer Interface.
  var/httpd/htdocs/skins/Customer/default/css/Core.Form.css
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for merge, 2 - Frontend

#298 Fixed uninitialized value warning in AdminSystemMaintenance.
  Kernel/Modules/AdminSystemMaintenance.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - Frontend

#301 Fixed hidden TicketOverview filters for Medium and Preview.
  Kernel/Output/HTML/TicketOverview/Medium.pm
  Kernel/Output/HTML/TicketOverview/Preview.pm
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 3 - wait for merge, 2 - Frontend, Znuny Feature

#317 Fixed reloading of the toolbar modules.
  Kernel/Modules/AgentDashboardCommon.pm
  Kernel/Output/HTML/Layout.pm
  Kernel/Output/HTML/Templates/Standard/Header.tt
  Kernel/Output/HTML/Templates/Standard/HeaderToolbar.tt
  var/httpd/htdocs/js/Core.Agent.Header.js
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 2 - Frontend, Znuny Latest, 3 - wait for pipeline

#333 Fixed "NoPermission" screen to use "CustomerNoPermission" for ACL checking.
  Kernel/Modules/CustomerTicketZoom.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for merge, 2 - Frontend

#334 Added SysConfig setting to configure format tags in rich text editor.
  Kernel/Config/Files/XML/Framework.xml
  var/httpd/htdocs/js/Core.UI.RichTextEditor.js
Labels: 1 - 🚀 feature, 4 - verified, 3 - wait for merge, 2 - Frontend, Znuny Feature

#327 Sort values in AdminDynamicFieldScreenConfiguration
  Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
Labels: 1 - 🚀 feature, 4 - verified, 1 - 💎 code quality, 2 - Frontend
