Repository znuny/Znuny, pull requests merged in 2023-11, with the labels that each got.

#299 Fixed queue_id entry in ticket history for the initial ticket
  scripts/database/initial_insert.mysql.sql
  scripts/database/initial_insert.oracle.sql
  scripts/database/initial_insert.postgresql.sql
  scripts/database/initial_insert.xml
Labels: 4 - verified, 1 - 💎 code quality, 3 - wait for merge

#489 Sector Nord AG: Textarea element now expands in both directions.
  var/httpd/htdocs/skins/Agent/default/css/Core.Form.css
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for merge, 2 - Frontend

#487 Sector Nord AG: Resolved CTRL+left click on ticket error message.
  var/httpd/htdocs/js/Core.Agent.Overview.js
Labels: 1 - 🐞 bug 🐞, 4 - verified

#486 SectorNordAG: Fixed format of file content in AdminPackageManager's ViewDiff mask
  Kernel/Modules/AdminPackageManager.pm
  Kernel/Output/HTML/Templates/Standard/AdminPackageManager.tt
Labels: 1 - 🐞 bug 🐞, 4 - verified

#390 Configurable resolver timeout
  Kernel/Config/Files/XML/Framework.xml
  Kernel/System/CheckItem.pm
Labels: 1 - 🚀 feature, 4 - verified
