Repository znuny/Znuny, pull requests merged in 2023-07, with the labels that each got.

#308 Sector Nord AG: Fixed Calendar appointment plugin AppointmentID data type.
  scripts/Migration/Znuny/UpgradeDatabaseStructure.pm
  scripts/Migration/Znuny/UpgradeDatabaseStructure/CalendarAppointmentID.pm
  scripts/database/schema.mysql.sql
  scripts/database/schema.oracle.sql
  scripts/database/schema.postgresql.sql
  scripts/database/schema.xml
Labels: 1 - 🐞 bug 🐞, 1 - 💎 code quality, 2 - Database, Znuny Feature

#458 Fixed mentions for deleted tickets.
  Kernel/System/Mention.pm
  Kernel/System/Ticket.pm
  scripts/Migration.pm
  scripts/Migration/Znuny/CleanupOrphanedMentions.pm
Labels: 1 - 🐞 bug 🐞, 3 - wait for merge

#368 orphaned session records not cleaned (#329)
  Kernel/System/AuthSession.pm
  Kernel/System/Console/Command/Maint/Session/DeleteOrphaned.pm
  Kernel/System/Console/Command/Maint/Session/ListOrphaned.pm
  scripts/test/RemoveOrphanedSessions.t
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for reviewer

#300 Fixed double encoding for dynamic field values in the linked-tickets-table
  Kernel/Output/HTML/LinkObject/Ticket.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Frontend, Znuny Feature, Znuny Latest

#325 BUG fixed: responsible user id isn't set correctly during appointment…
  Kernel/System/Calendar/Plugin/Ticket/Create.pm
  scripts/test/Calendar/Plugin/Ticket/Create.t
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 3 - wait for reviewer, 3 - wait for merge, 2 - Backend, Znuny Feature

#295 Fixed remove of mention and unnecessary errors in the log
  Kernel/System/Mention.pm
  var/httpd/htdocs/js/Znuny.Agent.MentionAction.js
  var/httpd/htdocs/js/Znuny.Agent.TicketMention.js
Labels: 1 - 🐞 bug 🐞, 3 - wait for reviewer, 3 - wait for merge, 2 - Frontend, 2 - Backend
