Repository znuny/Znuny, pull requests merged in 2023-08, with the labels that each got.

#75 Fixed handling whitespaces around '=' in Content-Type/charset token.
  Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm
  Kernel/GenericInterface/Operation/Ticket/TicketUpdate.pm
  Kernel/GenericInterface/Transport/HTTP/REST.pm
  Kernel/GenericInterface/Transport/HTTP/SOAP.pm
  Kernel/Output/HTML/Article/MIMEBase.pm
  Kernel/Output/HTML/Layout.pm
  Kernel/Output/HTML/Layout/Article.pm
  Kernel/System/EmailParser.pm
  Kernel/System/ProcessManagement/TransitionAction/Base.pm
  Kernel/System/Ticket/Article/Backend/MIMEBase.pm
  scripts/test/Layout/RichTextDocumentServe.t
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 3 - wait for merge, 2 - Backend, Znuny Feature

#475 SectorNordAG: Fixed missing $ on StartDateTimeObject -> $StartDateTimeObject
  Kernel/System/GenericAgent/NotifyAgentGroupOfCustomQueue.pm
  Kernel/System/GenericAgent/NotifyAgentGroupWithWritePermission.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - Backend, Znuny Feature

#469 Fixed display of pending time selection
  Kernel/Output/HTML/Templates/Standard/AgentTicketBulk.tt
  Kernel/Output/HTML/Templates/Standard/AgentTicketCompose.tt
  Kernel/Output/HTML/Templates/Standard/AgentTicketMove.tt
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for reviewer, 2 - Frontend, Znuny Feature

#478 Fixed some Selenium tests.
  .mailmap
  scripts/test/Selenium/Agent/Admin/AdminGenericAgent.t
  scripts/test/Selenium/Agent/Admin/AgentTicketEmailPGP.t
  scripts/test/Selenium/Agent/AgentCustomerUserInformationCenter.t
  scripts/test/Selenium/Agent/AgentDashboardCommon.t
  scripts/test/Selenium/Agent/AgentStatistics/Add.t
  scripts/test/Selenium/Agent/AgentStatistics/Overview.t
  scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketNote.t
  scripts/test/Selenium/Agent/AgentTicketEmailOutbound.t
  scripts/test/Selenium/Agent/AgentTicketQueue.t
  scripts/test/Selenium/Agent/AgentTicketSearch.t
  scripts/test/Selenium/Agent/Ajax/ErrorHandling.t
  scripts/test/Selenium/Agent/DynamicFieldShowLink.t
  scripts/test/Selenium/Agent/Responsive/Basic.t
  scripts/test/Selenium/Agent/Responsive/Popups.t
  scripts/test/Selenium/Output/TicketZoom/CustomerInformation.t
  scripts/test/Selenium/Output/TicketZoom/TicketInformation.t
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 2 - UnitTest

#484 Fixed Selenium tests for AgentStatistics.
  scripts/test/Selenium/Agent/AgentStatistics/Import.t
  scripts/test/Selenium/Agent/AgentStatistics/Run.t
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - UnitTest

#482 Fixed Selenium test AdminCustomerUserService.t
  scripts/test/Selenium/Agent/Admin/AdminCustomerUserService.t
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - UnitTest

#481 Fixed removing filter parameters not working correctly in AgentCustomerUserAddressBook.
  Kernel/Output/HTML/Templates/Standard/AgentCustomerUserAddressBook.tt
  var/httpd/htdocs/js/Core.Agent.CustomerUserAddressBook.js
Labels: 1 - 🐞 bug 🐞, 4 - verified, 2 - Frontend, Znuny Feature

#480 Fixed AdminPGP missing breadcrumb entry and failing Selenium test.
  Kernel/Output/HTML/Templates/Standard/AdminPGP.tt
  scripts/test/Selenium/Agent/Admin/AdminPGP.t
Labels: 1 - 🐞 bug 🐞, 1 - 💎 code quality, 2 - Frontend, 2 - UnitTest

#485 Fixed extra space causing uninitialized value error.
  Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewSmall.tt
Labels: 1 - 🐞 bug 🐞, 4 - verified, 1 - 💎 code quality, 2 - Frontend
