Repository znuny/Znuny, pull requests merged in 2023-06, with the labels that each got.

#446 Added Translate() to CustomerTicketProcess PageTitle.
  Kernel/Output/HTML/Templates/Standard/CustomerTicketProcess.tt
Labels: 1 - 🐞 bug 🐞, Znuny LTS, 4 - verified, 1 - 💎 code quality, 3 - wait for merge, 2 - Frontend, Znuny Feature

#266 Changed AgentTicketProcess to always fill rich text editor configs.
  Kernel/Modules/AgentTicketProcess.pm
Labels: 1 - 🚀 feature, 4 - verified, 3 - wait for merge, 2 - Frontend

#73 Added ExternalFQDN parameter for better security.
  Kernel/Config/Files/XML/Framework.xml
  Kernel/System/Calendar/Appointment.pm
  Kernel/System/Email.pm
  Kernel/System/HTMLUtils.pm
  Kernel/System/Ticket/Article/Backend/Email.pm
  Kernel/System/Web/UploadCache/DB.pm
  Kernel/System/Web/UploadCache/FS.pm
Labels: 1 - 🚀 feature, 4 - verified, 3 - wait for merge, 2 - Backend, Znuny Feature
