Repository znuny/Znuny, pull requests merged in 2024-02, with the labels that each got.

#528 Add html comment end tag
  Kernel/Output/HTML/Templates/Standard/Copyright.tt
Labels: 4 - verified

#346 Added missing TicketID in ArticleList.
  Kernel/Modules/AgentTicketPhoneCommon.pm
Labels: 1 - 🐞 bug 🐞, 3 - wait for reviewer

#530 Add html comment end tag
  Kernel/Output/HTML/Templates/Standard/Copyright.tt
Labels: 4 - verified

#498 SectorNordAG: Clicking 'Enter' inside of <input> triggers wrong event.
  var/httpd/htdocs/js/Core.Form.js
Labels: 4 - verified, 3 - wait for merge

#397 Notification templates initialization fix
  scripts/database/initial_insert.mysql.sql
  scripts/database/initial_insert.oracle.sql
  scripts/database/initial_insert.postgresql.sql
  scripts/database/initial_insert.xml
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for merge

#406 Fixed generic agent scheduled jobs immediate executions after schedule change
  Kernel/System/GenericAgent.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified, 3 - wait for merge
