Repository znuny/Znuny, pull requests merged in 2024-04, with the labels that each got.

#551 Sector Nord AG: Added AgentTicketNoteToLinkedTicket to screen configuration
  Kernel/Config/Files/XML/Znuny.xml
  scripts/test/DynamicField/ScreenConfiguration.t
Labels: 4 - verified, 1 - 💎 code quality

#544 Sector Nord AG: Fixed used config in ticket owner toolbar.
  Kernel/Output/HTML/ToolBar/TicketOwner.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified

#502 [GenericInterface] 2FA was added
  Kernel/GenericInterface/Operation/Session/Common.pm
  Kernel/GenericInterface/Transport/HTTP/REST.pm
Labels: 1 - 🚀 feature, 4 - verified
