Repository znuny/Znuny, pull requests merged in 2024-11, with the labels that each got.

#576 Added configurable InputFields::ModernizedSelection::MaxNumberOfOptions.
  Kernel/Config/Files/XML/Framework.xml
  Kernel/Language/de.pm
  Kernel/Output/HTML/Layout.pm
  var/httpd/htdocs/js/Core.UI.InputFields.js
Labels: 1 - 🚀 feature, 4 - verified, 3 - wait for merge

#589 Fixed link in INSTALL.md / UPDATING.md (#589)
  INSTALL.md
  UPDATING.md
Labels: 4 - verified, 3 - wait for merge

#611 Sector Nord AG: Fixed uninitialized value in AdminSelectBox
  Kernel/Modules/AdminSelectBox.pm
Labels: 1 - 🐞 bug 🐞, 4 - verified
