Repository znuny/Znuny, pull requests merged in 2025-09, with the labels that each got.

#705 Sector Nord AG: Fixed duplicate favorites in AdminMenu.
  var/httpd/htdocs/skins/Agent/default/css/Core.Agent.Admin.css
Labels: 3 - verified, 2 - wait for merge, 3 - internal Issue/MR

#692 Sector Nord AG: Fixed misplaced attachment tooltip.
  var/httpd/htdocs/js/Core.Form.ErrorTooltips.js
Labels: 1 - 🐞 bug 🐞, 3 - verified, 2 - work in progress, 3 - internal Issue/MR

#703 SectorNord AG: Fixed Bug - Problem filtering by Owner in the ticket view. #698
  Kernel/System/Ticket/ColumnFilter.pm
  var/httpd/htdocs/js/Core.Agent.Overview.js
Labels: 1 - 🐞 bug 🐞, 3 - verified, 3 - internal Issue/MR

#647 IT.WESER-EMS: Add prio param to AgentTicketZoom MenuModules for individual sorting
  Kernel/Config/Files/XML/Calendar.xml
  Kernel/Config/Files/XML/ProcessManagement.xml
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/Config/Files/XML/Znuny.xml
  Kernel/Modules/AgentTicketZoom.pm
Labels: 1 - 🚀 feature, 3 - verified, 3 - internal Issue/MR
